### PR TITLE
Composable for getting component by id

### PR DESCRIPTION
**Pull request by p1pchenk0**

### CODE REVIEW

**Comment by p1pchenk0** [comment]
`import { useCwaComponent } from '#imports'` works and should be familiar for developers
but we can introduce separate alias

**Comment by p1pchenk0** [comment]
import { useCwaComponent } from '#imports' works and should be familiar for developers
but we can introduce separate alias

**Comment by p1pchenk0** [comment]
Tbh, `#imports` alias is already pretty magical thing :)
And if other devs use other stuff, it should reduce amount of import lines (little, but still)

**Comment by silverbackdan** [comment]
:) cool I like using the `#imports` we can just document what we have available as they grow, no need to add complexity

**Comment by silverbackdan** [comment]
I wonder if in this composable we simple export a const for a developer to include in their `defineProps`
```
export const cwaComponentProps = {
  iri: {
    type: String,
    required: true
  }
}
```

Then the DX is to to this in their component:
```
const props = defineProps(cwaComponentProps)
```
or if they need more
```
const props = defineProps({
  ...cwaComponentProps,
  // more props here
})
```

**Comment by p1pchenk0** [comment]
Ok, I've changed the name of composable and also moved prop into const
I think it would be nice to have it named like actual prop name, so it would make less cognitive load on devs:
```javascript
import { useCwaResource, iri } from '#imports'

const props = defindeProps({
  ...iri,
  // some other props go here
})

//...

const resource = useCwaResource(props.iri) // iri is now well-known :)
```

**Pull request merged**
