### PR TITLE
Move eventBus into Admin class

### PR DESCRIPTION
**Pull request by p1pchenk0**
- [x] moved event bus to Admin class
- [x] updated unit tests

### CODE REVIEW

**Comment by silverbackdan** [comment]
It happens to me too. Delete lock files, node modules, reinstall and it should fail and fix it

**Comment by silverbackdan** [comment]
If you can get that fixed then I'll happily merge :)

**Comment by p1pchenk0** [comment]
I was trying to reinstall all packages, but now getting connection timeouts (opening link in browser works fine):
image
Haven't had this before...

**Comment by silverbackdan** [comment]
The registry may be down or having troubles let's check

**Comment by silverbackdan** [comment]
Hmmm seems OK https://status.npmjs.org/ at least so far
give it a few minutes perhaps , might be rate limiting you - no rush for today. You can continue with whichever task takes your fancy tomorrow. We can finish and merge this first and I you can do whatever you need. I've decided to get other work done while you do this so we don't end up working on the same files and causing conflicts :) I'll be around all day if you have any questions etc.

**Comment by p1pchenk0** [comment]
looks like an issue with how pnpm forces to use ipv6 addresses, will try forcing it to use ipv4
https://github.com/pnpm/pnpm/issues/6434

**Comment by silverbackdan** [comment]
How odd, hmm, ok see what you can do :)

**Comment by p1pchenk0** [comment]
ready

**Comment by silverbackdan** [comment]
Thanks!

**Pull request merged**
